name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: doc2quarto
            asset_name: doc2quarto-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: doc2quarto
            asset_name: doc2quarto-macos-aarch64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: doc2quarto
            asset_name: doc2quarto-linux-x86_64
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Strip binary (Linux/macOS)
        run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
      
      - name: Create tarball
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
          cd -
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}
